# CI/CD workflow for barcode-data-portal-mwlr
#
# Security Model:
# - CI builds and pushes images to Artifactory
# - ArgoCD Image Updater automatically deploys to dev
# - NO GitOps repo access from CI
#
# Required secrets:
# - ARTIFACTORY_HOST
# - ARTIFACTORY_USERNAME  
# - ARTIFACTORY_TOKEN

name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    uses: manaakiwhenua/github-workflows/.github/workflows/docker-build.yml@main
    with:
      bake_file: docker-bake.hcl
      bake_target: default
      push: ${{ github.event_name != 'pull_request' }}
    secrets:
      ARTIFACTORY_HOST: ${{ secrets.ARTIFACTORY_HOST }}
      ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
      ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}

  summary:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Deployment summary
        run: |
          cat << SUMMARY >> $GITHUB_STEP_SUMMARY
          ## ✅ Build Complete
          
          | Property | Value |
          |----------|-------|
          | Build ID | \`${{ needs.build.outputs.build_id }}\` |
          
          ### Dev Deployment
          
          🔄 ArgoCD Image Updater will automatically deploy to dev.
          
          ### Prod Promotion
          
          Create a PR in k8s-apps-config with build ID: \`${{ needs.build.outputs.build_id }}\`
          SUMMARY
