# Example CI/CD workflow for barcode-data-portal-mwlr
#
# Place this at .github/workflows/ci.yml in the barcode-data-portal-mwlr repository

name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    uses: manaakiwhenua/github-workflows/.github/workflows/docker-build.yml@main
    with:
      bake_file: docker-bake.hcl
      bake_target: default
      push: ${{ github.event_name != 'pull_request' }}
    secrets:
      ARTIFACTORY_HOST: ${{ secrets.ARTIFACTORY_HOST }}
      ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
      ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}

  deploy-dev:
    needs: build
    if: github.ref == 'refs/heads/main'
    uses: manaakiwhenua/github-workflows/.github/workflows/k8s-deploy.yml@main
    with:
      environment: dev
      cluster: tak-k8s-nonprod
      build_id: ${{ needs.build.outputs.build_id }}
    secrets:
      ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}
      GITOPS_SSH_KEY: ${{ secrets.GITOPS_SSH_KEY }}
