# Example: Complete CI/CD workflow for a consumer repository
#
# Security Model:
# - CI builds and pushes images to Artifactory
# - Deploy step triggers k8s-apps-config pipeline (no direct GitOps write access)
# - k8s-apps-config validates request and commits/creates PR
# - Nonprod: direct commit to main
# - Prod: creates PR requiring approval
#
# This workflow has NO write access to the GitOps repository.
# It only has permission to trigger pipelines in k8s-apps-config.

name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Build and push Docker images
  build:
    uses: manaakiwhenua/github-workflows/.github/workflows/docker-build.yml@main
    with:
      bake_file: docker-bake.hcl
      bake_target: default
      # Only push on main branch, not PRs
      push: ${{ github.event_name != 'pull_request' }}
    secrets:
      ARTIFACTORY_HOST: ${{ secrets.ARTIFACTORY_HOST }}
      ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
      ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}

  # Deploy to dev (automatic)
  deploy-dev:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to dev
        uses: manaakiwhenua/github-workflows/actions/k8s-deploy@main
        with:
          app_name: ${{ github.event.repository.name }}
          environment: dev
          cluster: tak-k8s-nonprod
          build_key: ${{ needs.build.outputs.build_id }}
          bitbucket_token: ${{ secrets.K8S_APPS_CONFIG_TRIGGER_TOKEN }}

  # Deploy to test (manual)
  deploy-test:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: test  # Requires manual approval in GitHub
    steps:
      - name: Deploy to test
        uses: manaakiwhenua/github-workflows/actions/k8s-deploy@main
        with:
          app_name: ${{ github.event.repository.name }}
          environment: test
          cluster: tak-k8s-nonprod
          build_key: ${{ needs.build.outputs.build_id }}
          bitbucket_token: ${{ secrets.K8S_APPS_CONFIG_TRIGGER_TOKEN }}

  # Deploy to prod (manual + creates PR in k8s-apps-config)
  deploy-prod:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production  # Requires manual approval in GitHub
    steps:
      - name: Deploy to prod
        id: deploy
        uses: manaakiwhenua/github-workflows/actions/k8s-deploy@main
        with:
          app_name: ${{ github.event.repository.name }}
          environment: prod
          cluster: tak-k8s-prod
          build_key: ${{ needs.build.outputs.build_id }}
          bitbucket_token: ${{ secrets.K8S_APPS_CONFIG_TRIGGER_TOKEN }}
          wait: 'false'  # Don't wait - PR needs human approval
      
      - name: Summary
        run: |
          cat << SUMMARY >> $GITHUB_STEP_SUMMARY
          ## 🚀 Production Deployment Initiated
          
          A Pull Request has been created in k8s-apps-config.
          
          **Next steps:**
          1. Review the PR in Bitbucket
          2. Approve and merge to deploy to production
          
          | Property | Value |
          |----------|-------|
          | Pipeline | [${{ steps.deploy.outputs.pipeline_uuid }}](${{ steps.deploy.outputs.pipeline_url }}) |
          | Image Tag | \`${{ needs.build.outputs.build_id }}\` |
          SUMMARY
