# Example: Complete CI/CD workflow for a consumer repository
#
# Security Model:
# - CI builds and pushes images to Artifactory (no GitOps access)
# - ArgoCD Image Updater automatically deploys to dev
# - Prod requires manual PR to k8s-apps-config (human approval)
#
# This workflow has NO write access to the GitOps repository.

name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Build and push Docker images
  build:
    uses: manaakiwhenua/github-workflows/.github/workflows/docker-build.yml@main
    with:
      bake_file: docker-bake.hcl
      bake_target: default
      # Only push on main branch, not PRs
      push: ${{ github.event_name != 'pull_request' }}
    secrets:
      ARTIFACTORY_HOST: ${{ secrets.ARTIFACTORY_HOST }}
      ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
      ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}

  # Summary job - dev deployment happens automatically via Image Updater
  summary:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Deployment summary
        run: |
          cat << SUMMARY >> $GITHUB_STEP_SUMMARY
          ## ✅ Build Complete
          
          | Property | Value |
          |----------|-------|
          | Build ID | \`${{ needs.build.outputs.build_id }}\` |
          | Registry | \`${{ needs.build.outputs.registry_prefix }}\` |
          
          ### 🔄 Dev Deployment
          
          ArgoCD Image Updater will automatically detect the new images and deploy to dev.
          
          ### 🚀 Prod Promotion
          
          To promote to production:
          1. Clone k8s-apps-config
          2. Update prod manifests with build ID: \`${{ needs.build.outputs.build_id }}\`
          3. Create a Pull Request
          4. Get approval and merge
          SUMMARY
